INSERT INTO SECURITY (TICKER_ID, SECURITY_TYPE) VALUES ('AAPL', 'STOCK');
INSERT INTO SECURITY (TICKER_ID, SECURITY_TYPE) VALUES ('TSLA', 'STOCK');
INSERT INTO SECURITY (TICKER_ID, SECURITY_TYPE) VALUES ('AAPL-OCT-2020-110-C', 'CALL');
INSERT INTO SECURITY (TICKER_ID, SECURITY_TYPE) VALUES ('AAPL-OCT-2020-110-P', 'PUT');
INSERT INTO SECURITY (TICKER_ID, SECURITY_TYPE) VALUES ('TELSA-NOV-2020-400-C', 'CALL');
INSERT INTO SECURITY (TICKER_ID, SECURITY_TYPE) VALUES ('TELSA-DEC-2020-400-P', 'PUT');