INSERT INTO SECURITY (TICKER_ID, LAST_STOCK_PRICE, SECURITY_TYPE, STOCK_RETURN, ANNUAL_STD_DEV) VALUES ('AAPL', 226.84, 'STOCK', 0.05, 0.02 );
INSERT INTO SECURITY (TICKER_ID, LAST_STOCK_PRICE, SECURITY_TYPE, STOCK_RETURN, ANNUAL_STD_DEV) VALUES ('TSLA', 220.32, 'STOCK', 0.1, 0.07);
INSERT INTO SECURITY (TICKER_ID, LAST_STOCK_PRICE, SECURITY_TYPE, STRIKE,       MATURITY) VALUES ('AAPL-OCT-2024-110-C', 226.84, 'CALL', 0.95,6);
INSERT INTO SECURITY (TICKER_ID, LAST_STOCK_PRICE, SECURITY_TYPE ,STRIKE,       MATURITY) VALUES ('AAPL-OCT-2024-110-P', 226.84, 'PUT', 1.10, 3);
INSERT INTO SECURITY (TICKER_ID, LAST_STOCK_PRICE, SECURITY_TYPE, STRIKE,       MATURITY) VALUES ('TELSA-NOV-2024-400-C', 220.32, 'CALL', 0.90, 1);
INSERT INTO SECURITY (TICKER_ID, LAST_STOCK_PRICE, SECURITY_TYPE, STRIKE,       MATURITY) VALUES ('TELSA-DEC-2024-400-P', 220.32, 'PUT', 1.15, 2);